### ISSUE TITLE
This action is using a deprecated action

### ISSUE THREAD

**Issue by ruettenm** [dcodeIO/setup-node-nvm#6]
Fist of all thank for this action. It works as expected 👍 

But when using it I saw the following warning from github. I guess it makes sense to solve this soon. 

```
The `add-path` command is deprecated and will be disabled soon. 
Please upgrade to using Environment Files. For more information see: 
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

**Comment by dcodeIO** [comment]
I've updated the respective dependencies in https://github.com/dcodeIO/setup-node-nvm/pull/7. Can you confirm that the warning did go away (using `setup-node-nvm@master`)?

**Comment by ruettenm** [comment]
Yes, thanks :+1:

**Comment by ljharb** [comment]
To be clear, this means that https://github.blog/changelog/2020-11-09-github-actions-removing-set-env-and-add-path-commands-on-november-16/ will no longer impact this action?

**Comment by dcodeIO** [comment]
Afaict, yes. It now uses the updated `@actions/core` module that in turn utilizes the patched mechanism to set environment variables. It was not using the STDOUT related functionality.

**Comment by ljharb** [comment]
Awesome, thanks. I'm the nvm maintainer, and I was stoked to find this action (which I'm beginning to reuse on hundreds of projects) to help me migrate off of travis.
